name: Publish libappindicator-gtk3-java-minimal to Maven Central

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # only allow publishing tagged versions

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'minimal'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Import GPG key
        run: |
          echo "$GPG_SIGNING_KEY_PW" | gpg --batch --import --yes --passphrase-fd 0 <(echo -n "$GPG_SIGNING_KEY_B64" | base64 --decode)
        env:
          GPG_SIGNING_KEY_B64: ${{ secrets.GPG_PRIVATE_KEY_B64 }}
          GPG_SIGNING_KEY_PW: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup GPG key information
        run: |
          mkdir -p ~/.gradle
          echo "signing.gnupg.passphrase=${GPG_SIGNING_KEY_PW}" >> ~/.gradle/gradle.properties
        env:
          GPG_SIGNING_KEY_PW: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build package
        run: ./gradlew clean build

      - name: Publish package
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}